### ISSUE TITLE
Possible to fix artifacting in MGS2/3?

### ISSUE THREAD

**Issue by ChapyGuy** [Lyall/MGSHDFix#84] opened 2023-12-26 23:12 UTC
This is happening for me with a vanilla install, but I wanted to ask if this mod could possibly fix the artifacting issues I'm having. Moments like the examples I attached can be seen all over MGS2 and 3. 
I'm on Windows 10 build 19045, with a Ryzen 3700x and a Radeon RX 6800 XT
![image psd(1)](https://github.com/Lyall/MGSHDFix/assets/97793456/c9bfd9d1-4b76-4eb4-b807-031ec7520ff2)
![image psd](https://github.com/Lyall/MGSHDFix/assets/97793456/ab727957-84b0-4992-ac15-caade1cb2de4)

**Comment by ChapyGuy** [comment] 2023-12-26 23:51
I found a better video example in a reddit thread. Probably an AMD issue.
https://youtu.be/1fZd4B9PHr4

**Comment by ShizCalev** [comment] 2023-12-27 18:40
Duplicate of #22

**Comment by ShizCalev** [comment] 2023-12-27 18:41
Known issue with AMD gpus, it happens in the vanilla game without this mod, so be sure to report it to Konami here as well 
https://us-support.konami.com/hc/en-us/requests/new

**Comment by cipherxof** [comment] 2023-12-28 00:20
Similar issues also happened via emulation in RPCS3.

**Comment by ChapyGuy** [comment] 2023-12-28 06:28
I reported it with Konami with the link you shared. I believe it's part of the post processing that's broken, and it becomes less noticeable at higher resolutions. At the default 720p like in the video it's very noticeable, but at 4k it's a very small line of artifacts.

**Comment by ChapyGuy** [comment] 2023-12-28 06:42
Using DXVK Async fixes the artifacting. MGS2 and 3 need to be windowed, and then you can use a program like Borderless Gaming to force borderless windowed mode. Swapping to windowed borderless with alt+enter causes the game to crash.

**Closed** 2024-01-05 23:03 UTC

**Comment by LorenzoKy** [comment] 2024-01-24 23:35
did they fix artifacting with the latest drivers or am i trippin?

**Comment by OddOttAllen** [comment] 2024-01-25 00:17
> did they fix artifacting with the latest drivers or am i trippin?

i can confirm it's fixed for me too, after updating!

**Comment by LorenzoKy** [comment] 2024-01-25 01:53
> > did they fix artifacting with the latest drivers or am i trippin?
> 
> i can confirm it's fixed for me too, after updating!

oh finally
