### ISSUE TITLE
Possible to swap O/X for confirm/cancel?

### ISSUE THREAD

**Issue by Rezulux** [Lyall/MGSHDFix#56] opened 2023-11-12 02:37 UTC
I'm so used to the classic controls in Metal Gear games that having X as confirm and O as cancel actually trips me up a lot, is it possible to have an option to swap these just for their menu purposes without affecting their actual ingame function?

Not sure if this is beyond the scope of this project but I figured I'd suggest it!

**Comment by ShizCalev** [comment] 2024-01-10 21:03
You don't need MGSHDFix to do this actually, just swapping controller binds fully supports the old menu inputs without changing any other behavior. 

MGS2: Look for my Swapped X/O bind

![image](https://github.com/Lyall/MGSHDFix/assets/6209658/f9001e65-8e8b-48c9-a7bd-8af9d9bed0ac)

MGS3: Look for my Original X/O menu bind. 
![image](https://github.com/Lyall/MGSHDFix/assets/6209658/7bdf4d36-e843-402d-98ed-2818a9e2e0bf)

**Comment by Lyall** [comment] 2024-01-25 19:22
That seems like a great way of doing it using Steam Input @ShizCalev.

Closing this as dupe of #34. Please direct any further remapping issues/requests to that.

**Closed by Lyall** 2024-01-25 19:22 UTC
