### ISSUE TITLE
Fix possible issues with Gamma?

### ISSUE THREAD

**Issue by Durandline** [Lyall/MGSHDFix#40] opened 2023-11-02 14:29 UTC
It seems as if Konami messed up the gamma levels of MGS2 and 3 when porting it over to The Master Collection.  Possibly add in a fix for this?  Seems like it would be easy to do so.

Examples at 1:17 and 4:24, not the most professional I know, but it's my first github post.
https://www.youtube.com/watch?v=gNBuXuHr6qs

**Comment by MarioTainaka** [comment] 2023-11-03 10:34
This mod is a reshde preset that fixes the gamma ideally something like this could be added as an ini toggle

https://www.nexusmods.com/metalgearsolidmastercollection/mods/22

**Comment by ShizCalev** [comment] 2024-01-10 21:06
Updated link to the gamma mod:

https://www.nexusmods.com/metalgearsolid3mc/mods/29

It also works perfectly for MGS2.

**Comment by Lyall** [comment] 2024-01-25 19:19
Kind of a dupe of #58. @ShizCalev's mod looks like the way to go

**Closed by Lyall** 2024-01-25 19:19 UTC
