### ISSUE TITLE
Highly recommend you add volume sliders for this game.

### ISSUE THREAD

**Issue by Durandline** [Lyall/MGSHDFix#61] opened 2023-11-14 17:05 UTC
The audio mixing is terrible and some sounds are louder than they should be.

**Comment by ShizCalev** [comment] 2023-11-14 23:29
https://www.nexusmods.com/metalgearsolidmastercollection/mods/7

Duplicate of #53

**Comment by mntorankusu** [comment] 2023-11-15 06:01
> Mods already fix that.
> 
> https://www.nexusmods.com/metalgearsolidmastercollection/mods/6
> 
> https://www.nexusmods.com/metalgearsolidmastercollection/mods/7
> 
> Duplicate of #53

That mod doesn't fix the poor mixing. It only changes the audio streams used for cutscenes and calls.

And if the poor sound quality is to any degree caused by clipping in the final mix and not just the sound files themselves, then fixing it via a mod like this makes a lot more sense than replacing every audio file in the game.

**Comment by Durandline** [comment] 2023-11-20 08:46
> > Mods already fix that.
> > https://www.nexusmods.com/metalgearsolidmastercollection/mods/6
> > https://www.nexusmods.com/metalgearsolidmastercollection/mods/7
> > Duplicate of #53
> 
> That mod doesn't fix the poor mixing. It only changes the audio streams used for cutscenes and calls.
> 
> And if the poor sound quality is to any degree caused by clipping in the final mix and not just the sound files themselves, then fixing it via a mod like this makes a lot more sense than replacing every audio file in the game.

Actually it **is** the sound files that cause the clipping.  I checked it on The Xbox 360 version and it's there as well.  They just ported the Xbox 360 version, made no changes whatsoever, and somehow made it worse by blowing the audio out on top of the low quality sound files that were in place to make up for The DVDs lack of space.  Leave it up to Konami to reach new bars of laziness.

**Comment by ShizCalev** [comment] 2024-01-07 21:42
No longer needed

**Closed** 2024-01-25 19:13 UTC
