### ISSUE TITLE
[Bug] [MGS 3]: I just found out about your amazing work and Version 2.0.0 ruined it!

### ISSUE THREAD

**Issue by Jamezlap** [Lyall/MGSHDFix#107] opened 2024-09-25 11:36 UTC
I downloaded the HDFIX for Mgs vol. 1 and Konami decided to ruin it for me with their new patch! I can't play on ultra wide screen anymore :( when i put 5120 x 1440 it only shows the game on the left side of my screen. Please Lyall save me!!!

**Comment by Aelzaire** [comment] 2024-09-25 20:50
Can confirm, new internal resolution settings with 2.0 override your fix's settings, unfortunately. At least, for the resolution. Seems window mode, skip launcher and etc still work. However now the UI numbers for gun ammo etc is off center with the icon and the internal res is clearly very low as the game is quite pixelated. Appreciate an update if/when it comes.

**Comment by ShizCalev** [comment] 2024-09-26 03:45
Duplicate of #106

**Comment by Lyall** [comment] 2024-09-28 23:34
Directing discussion to #106

**Closed by Lyall** 2024-09-28 23:34 UTC
Labels: bug
