### ISSUE TITLE
[Feature Request] [MGS2/MGS3]:  Gamma fix

### ISSUE THREAD

**Issue by mooms06** [Lyall/MGSHDFix#98] opened 2024-03-14 16:08 UTC
## Feature Summary:

The gamma is way too bright in these games, see the PS2 and PS3 version, they have the correct gamma.

### Is your proposal related to a problem?

Yes, gamme is broken in these games.

### Describe the solution you'd like

Is this possible to fix it by patching the games on the fly like you did for the other fixes ?

### Describe alternatives you've considered

There is [a fix based on reshade for MGS3 here](https://www.nexusmods.com/metalgearsolid3mc/mods/29), but I wasn't able to made it works, and an universal fix for all games would be better.

Thank you for reading.

**Comment by Lyall** [comment] 2024-03-21 14:21
Dupe of #58

**Closed by Lyall** 2024-03-21 14:21 UTC
Labels: feature-request
